//shared between FQServer and FQLicense

const int C_L_COMMAND_HELLO_FROM_CLIENT = 0;
const int C_L_COMMAND_WELCOME_FROM_SERVER = 1;
const int C_L_COMMAND_LOGON_REQUEST_FROM_CLIENT = 2;
const int C_L_COMMAND_MESSAGE_FROM_SERVER = 3;
const int C_L_COMMAND_LOGON_VERIFICATION_FROM_SERVER = 4;
const int C_L_COMMAND_TLM_AUTH = 10;
const int C_L_COMMAND_TOOLFISH_AUTH = 11;
const int C_L_COMMAND_RPG_AUTH = 12;
const int C_L_COMMAND_DSCROLL_AUTH = 13;

