//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by fq.rc
//
#define ID_IMPORT                       3
#define ID_EXPORT                       4
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_FQ_DIALOG                   102
#define IDP_SOCKETS_INIT_FAILED         103
#define IDR_MAINFRAME                   128
#define IDR_MAIN                        129
#define IDD_SERVER_SETUP                130
#define IDD_EDIT_CHOOSE                 131
#define IDR_P_MENU                      132
#define IDD_PLAYER_EDIT                 133
#define IDD_KARMA_TEXT                  134
#define IDD_SIMPLE_EDIT                 136
#define IDD_RATINGS_TEXT                137
#define IDD_GAME_SETTINGS               138
#define IDI_ICON1                       139
#define IDC_LOG                         1000
#define IDC_SOUND                       1001
#define IDC_PORT                        1002
#define IDC_SAPI_ENABLED                1003
#define IDC_ON                          1007
#define IDC_DEBUG                       1008
#define IDC_PLAYERS                     1009
#define IDC_STATUS                      1010
#define IDC_LOGON                       1011
#define IDC_PASSWORD                    1012
#define IDC_NAME                        1013
#define IDC_PARLOR                      1014
#define IDC_LAST_IP                     1015
#define IDC_OLD_IP                      1016
#define IDC_EMAIL                       1017
#define IDC_LIST_KARMA                  1017
#define IDC_MONEY                       1018
#define IDC_TURNS_LEFT                  1019
#define IDC_EXP                         1020
#define IDC_STRING                      1020
#define IDC_COMPILED                    1021
#define IDC_KARMA                       1021
#define IDC_LIST_RATINGS                1022
#define IDC_RATING                      1022
#define IDC_PLOTS                       1023
#define IDC_STARTING_MONEY              1024
#define IDC_LAST_LOGGED                 1024
#define IDC_STARTING_KARMA              1025
#define IDC_LUCK                        1025
#define IDC_TURNS_PER_DAY               1026
#define IDC_YANGS_SENT                  1026
#define IDC_BONUS_EXP                   1027
#define IDC_TAGS_RECIEVED               1027
#define IDC_STARTING_RATING             1028
#define IDC_YANGS_PER_DAY               1028
#define IDC_I_HP                        1028
#define IDC_STARTING_WOOD               1029
#define IDC_I_HP_MAX                    1029
#define IDC_STARTING_SILVER             1030
#define IDC_I_STRENGTH                  1030
#define IDC_STARTING_GOLD               1031
#define IDC_I_PSYCH                     1031
#define IDC_GAME_AGE                    1032
#define IDC_I_VISITS                    1032
#define IDC_AUTO_SAVE_MIN               1033
#define IDC_STARTING_LUCK               1033
#define IDC_NEW_DAY                     1034
#define IDC_RESET                       1035
#define IDC_ACTIVE                      1035
#define IDC_WOOD                        1036
#define IDC_STARTING_PLOTS              1036
#define IDC_SILVER                      1037
#define IDC_LUCK_ODDS                   1037
#define IDC_GOLD                        1038
#define IDC_RISK                        1038
#define IDC_LAST_TEXT                   1039
#define IDC_STARTING_HP                 1039
#define IDC_PLAYER_MIN                  1040
#define IDC_TODAYS_BPS                  1040
#define IDC_BONUS_LUCK                  1040
#define IDC_ANON_MIN                    1041
#define IDC_LAST_TEXT2                  1041
#define IDC_TRADE_BONUS                 1041
#define IDC_I_VISITS_PER_DAY            1042
#define IDC_LOGON_1                     1043
#define IDC_STARTING_STRENGTH           1043
#define IDC_LOGON_2                     1044
#define IDC_ADMINS_EMAIL                1044
#define IDC_MEM_FREE                    1045
#define IDC_NORMAL_ODDS                 1045
#define IDC_LOG_TEXT                    1046
#define IDC_SCRIPT_ODDS                 1046
#define IDC_REFRESH                     1047
#define IDC_NEWS                        1047
#define IDC_VIEW_LOG                    1047
#define IDC_LOGONS                      1048
#define IDC_IP_CHECK                    1048
#define IDC_TAGS_RECIEVABLE_PER_DAY     1048
#define IDC_ALWAYS                      1049
#define IDC_VIEW_ERROR                  1049
#define IDC_VIEW_LOG_DELETE             1050
#define IDC_TOURN_ACTIVE                1050
#define IDC_VIEW_ERROR_DELETE           1051
#define IDC_TOURN_DAYS                  1051
#define IDC_LICENSE_LOGON               1052
#define IDC_LOGONS_TOTAL                1052
#define IDC_TAGS_RECIEVABLE_PER_DAY2    1052
#define IDC_CHANGE_NAME_COST            1052
#define IDC_LICENSE_PASSWORD            1053
#define IDC_VIEW_STATS                  1053
#define IDC_B_ADVERTISE                 1054
#define IDC_LICENSE_DESCRIPTION         1055
#define IDC_HITS                        1055
#define IDC_LICENSE_GAME_NAME           1056
#define IDC_HITS_TOTAL                  1056
#define IDC_MAX_PLAYERS                 1057
#define IDC_B_MAINT_DELETE              1058
#define IDC_INACTIVE_DAYS               1059
#define IDC_SWEAR_FILTER                1060
#define IDC_B_MALE                      1061
#define IDC_LICENSE_FORCE_IP            1061
#define IDC_B_ATTACK                    1062
#define IDC_B_POLICE                    1063
#define IDC_COMBO_CUSTOM                1064
#define IDC_CUSTOM_EDIT                 1065
#define IDC_MAX_ONLINE                  1065
#define ID_SETTINGS_SERVERSETUP         32771
#define ID_SETTINGS_PLAYER_EDIT         32772
#define ID_OPTIONS_EDIT                 32773
#define ID_OPTIONS_BAN                  32774
#define ID_OPTIONS_KICK                 32775
#define ID_GAME_SETUP                   32776
#define ID_GAME_KARMA_TEXT              32777
#define ID_ABOUT_FQ                     32778
#define ID_KILLSERVER                   32779
#define ID_RATING_TEXT                  32780
#define ID_GAME_SETTINGS                32781
#define ID_GAME_NEWS                    32782
#define ID_GAME_NO_CUSTOMER             32783
#define ID_GAME_YANGS                   32784
#define ID_GAME_EVENTS                  32785
#define ID_GAME_EDIT_RISKS              32786
#define IDC_NEWSPAPER                   32787
#define IDC_RELOAD_TEXT                 32789
#define IDC_HTML_HELP                   32791
#define ID_BAN_LIST                     32792
#define ID_SWEAR_FILTER                 32793
#define IDD_HARD_SELL                   32796
#define IDD_SOFT_SELL                   32797
#define IDD_NEWS_CRIME                  32798
#define ID_GAME_YANGS_NICE              32799

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        141
#define _APS_NEXT_COMMAND_VALUE         32800
#define _APS_NEXT_CONTROL_VALUE         1066
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
